import '../../globals.css';
import type { Metadata } from 'next';
import Dashboard from '../../components/Dashboard';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en' className='h-full'>
      <body>
        <main>
          <Dashboard>{children}</Dashboard>
        </main>
      </body>
    </html>
  );
}
